name: Auth-React Tests - L2
on:
    workflow_call:
        inputs:
            fdi-version:
                description: "FDI Version"
                required: true
                type: string

            specs:
                description: "Spec Files"
                required: true
                type: string

            AUTH_REACT__LOG_DIR:
                description: AUTH_REACT__LOG_DIR
                required: true
                type: string

            AUTH_REACT__SCREENSHOT_DIR:
                description: AUTH_REACT__SCREENSHOT_DIR
                required: true
                type: string

            AUTH_REACT__APP_SERVER:
                description: AUTH_REACT__APP_SERVER
                required: true
                type: string

            AUTH_REACT__NODE_PORT:
                description: AUTH_REACT__NODE_PORT
                required: true
                type: string

            AUTH_REACT__TEST_MODE:
                description: AUTH_REACT__TEST_MODE
                required: true
                type: string

            AUTH_REACT__PORT:
                description: AUTH_REACT__PORT
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            max-parallel: 10
            fail-fast: false
            matrix:
                spec: ${{ fromJSON(inputs.specs) }}

        env:
            SUPERTOKENS_CORE_PORT: 3567
            SUPERTOKENS_CORE_HOST: localhost
            TEST_MODE: testing
            # Auth react setup envs
            AUTH_REACT__LOG_DIR: ${{ inputs.AUTH_REACT__LOG_DIR }}
            AUTH_REACT__SCREENSHOT_DIR: ${{ inputs.AUTH_REACT__SCREENSHOT_DIR }}
            AUTH_REACT__NODE_PORT: ${{ inputs.AUTH_REACT__NODE_PORT }}
            AUTH_REACT__APP_SERVER: ${{ inputs.AUTH_REACT__NODE_PORT }}
            AUTH_REACT__TEST_MODE: ${{ inputs.AUTH_REACT__TEST_MODE }}
            AUTH_REACT__PORT: ${{ inputs.AUTH_REACT__PORT }}
            SUPERTOKENS_API_KEY: ${{ secrets.SUPERTOKENS_API_KEY }}

        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: bissolli/gh-action-persist-workspace@v2
              with:
                  action: retrieve
                  artifactName: auth-react-${{ inputs.fdi-version }}

            - name: Get Node CDI versions
              id: node-cdi-versions
              uses: supertokens/get-supported-versions-action@main
              with:
                  has-cdi: true
                  working-directory: supertokens-node

            - uses: supertokens/get-versions-action@main
              id: versions
              with:
                  driver-name: node
                  fdi-version: ${{ inputs.fdi-version }}

            - name: Get last Node CDI version
              id: last-node-cdi-version
              run: |
                export lastVersion=$(echo '${{ steps.node-cdi-versions.outputs.cdiVersions }}' | jq -r '.[-1]')
                echo "lastNodeCdiVersion=$lastVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

            - name: Get Core version
              id: core-version
              uses: supertokens/get-versions-action@main
              with:
                  driver-name: node
                  cdi-version: ${{ steps.last-node-cdi-version.outputs.lastNodeCdiVersion }}
              env:
                  SUPERTOKENS_API_KEY: ${{ secrets.SUPERTOKENS_API_KEY }}

            - name: Start core
              run: docker compose up --wait
              working-directory: supertokens-web-js
              env:
                  SUPERTOKENS_CORE_VERSION: ${{ steps.core-version.outputs.coreVersionXy }}

            - uses: supertokens/auth-react-testing-action@main
              name: test ${{ matrix.spec }} for ${{ inputs.fdi-version }}
              with:
                  fdi-version: ${{ inputs.fdi-version }}
                  check-name-suffix: "[FDI=${{ inputs.fdi-version }}][Spec=${{ matrix.spec }}]"
                  path: supertokens-auth-react
                  spec: ${{ matrix.spec }}
                  retrieve-workspace: "false"

            - uses: mxschmitt/action-tmate@v3
              if: failure()
